
FROM ubuntu_opencascade_base:latest

RUN apt-get install -y libopenmpi-dev libhdf5-serial-dev mpi
RUN apt-get install -y libvtk9-qt-dev

WORKDIR /opt/VTK_OpenCascasde
WORKDIR /opt/QT-VTK-OpenCascade
